device: cuda

path:
  audio: /work/dataset
  ex_audio: /work/ex_dataset/audio
  ex_label: /work/ex_dataset/meta
  meta: /work/meta/training.csv
  test_meta: /work/meta/test.csv
  tensorboard: /work/log/tensorboard
  result: /work/results
  truth: /work/meta/test_truth.csv

audio:
  win_size_rate: 0.025 # winsize = win_size_rate * sr
  overlap: 0.5
  n_mels: 32
  n_channels: 1

augmentation:
  mixup:
    using: True
    mode: "loss_mixup" # loss_mixup or label_mixup
  gaussian_noise:
    using: True
    min_snr: 5.0
    max_snr: 20.0
  time_shift:
    using: True
    max_shift_sec: 0.2
    padding_mode: "replace" # or zero
  volume_control:
    using: True
    db_lim: 40
    mode: "cosine" # 'uniform', 'fade', 'cosine', 'sine'

training:
  data: "base" # base or extend
  model: "ConformerModel" # ConformerModel, GRUModel, resnet18, resnet34, resnet50, CRNN
  kfold: 3
  n_epoch: 30
  batch_size: 512
  lr: 0.001
