device: cuda

path:
  audio: /work/dataset
  ex_audio: /work/ex_dataset/audio
  ex_label: /work/ex_dataset/meta
  meta: /work/meta/training.csv
  test_meta: /work/meta/test.csv
  tensorboard: /work/log/tensorboard
  result: /work/results

audio:
  win_size_rate: 0.025 # winsize = win_size_rate * sr
  overlap: 0.5
  n_mels: 32

training:
  data: 'extend' # or base
  model: 'ConformerModel' # or GRUModel
  kfold: 3
  n_epoch: 20
  batch_size: 512
  lr: 0.001
