device: cuda

path:
  audio: /work/dataset
  meta: /work/meta/training.csv
  test_meta: /work/meta/test.csv
  tensorboard: /work/log/tensorboard
  result: /work/results

audio:
  win_size_rate: 0.025 # winsize = win_size_rate * sr
  overlap: 0.5
  n_mels: 32

training:
  kfold: 3
  n_epoch: 20
  batch_size: 512
  lr: 0.001
